name 'pdsoe'
maintainer 'Mike Butler'
maintainer_email 'michael.butler@progress.com'
license 'All Rights Reserved'
description 'Installs/Configures pdsoe'
version '1.3.0'
chef_version '>= 17.0'
depends 'chocolatey'
